"""Add menu_item_allergens association table

Revision ID: 08d3e2054895
Revises: 206c2802d4a4
Create Date: 2025-11-01 14:00:23.673068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d3e2054895'
down_revision: Union[str, Sequence[str], None] = '206c2802d4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_allergens',
    sa.Column('menu_item_id', sa.String(), nullable=False),
    sa.Column('allergen_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen_database.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('menu_item_id', 'allergen_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_allergens')
    # ### end Alembic commands ###
