"""add mental wellness logging tables

Revision ID: 60cef32d6c1f
Revises: 44d8dc6013cc
Create Date: 2025-10-26 15:34:18.939825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60cef32d6c1f"
down_revision: Union[str, Sequence[str], None] = "44d8dc6013cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mood_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("mood_score", sa.Numeric(precision=2, scale=0), nullable=False),
        sa.Column("encrypted_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mood_logs_created_at"), "mood_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_mood_logs_log_date"), "mood_logs", ["log_date"], unique=False
    )
    op.create_index(
        op.f("ix_mood_logs_user_id"), "mood_logs", ["user_id"], unique=False
    )
    op.create_table(
        "sleep_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("duration_hours", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("quality_score", sa.Numeric(precision=2, scale=0), nullable=False),
        sa.Column("encrypted_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sleep_logs_created_at"), "sleep_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_sleep_logs_log_date"), "sleep_logs", ["log_date"], unique=False
    )
    op.create_index(
        op.f("ix_sleep_logs_user_id"), "sleep_logs", ["user_id"], unique=False
    )
    op.create_table(
        "stress_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("log_date", sa.Date(), nullable=False),
        sa.Column("stress_level", sa.Numeric(precision=2, scale=0), nullable=False),
        sa.Column("encrypted_triggers", sa.Text(), nullable=True),
        sa.Column("encrypted_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stress_logs_created_at"), "stress_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_stress_logs_log_date"), "stress_logs", ["log_date"], unique=False
    )
    op.create_index(
        op.f("ix_stress_logs_user_id"), "stress_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stress_logs_user_id"), table_name="stress_logs")
    op.drop_index(op.f("ix_stress_logs_log_date"), table_name="stress_logs")
    op.drop_index(op.f("ix_stress_logs_created_at"), table_name="stress_logs")
    op.drop_table("stress_logs")
    op.drop_index(op.f("ix_sleep_logs_user_id"), table_name="sleep_logs")
    op.drop_index(op.f("ix_sleep_logs_log_date"), table_name="sleep_logs")
    op.drop_index(op.f("ix_sleep_logs_created_at"), table_name="sleep_logs")
    op.drop_table("sleep_logs")
    op.drop_index(op.f("ix_mood_logs_user_id"), table_name="mood_logs")
    op.drop_index(op.f("ix_mood_logs_log_date"), table_name="mood_logs")
    op.drop_index(op.f("ix_mood_logs_created_at"), table_name="mood_logs")
    op.drop_table("mood_logs")
    # ### end Alembic commands ###
