name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'proj2/frontend/**'
      - 'proj2/package.json'
      - 'proj2/tsconfig.json'
      - 'proj2/bun.lockb'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'proj2/frontend/**'
      - 'proj2/package.json'
      - 'proj2/tsconfig.json'
      - 'proj2/bun.lockb'

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: proj2
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Run test 
      run: bun run --filter frontend test

    - name: Build application
      run: bun run --filter frontend build

    - name: Test build artifacts
      run: |
        # Check that build artifacts exist
        cd frontend
        test -f dist/index.html
        test -d dist/assets
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: proj2/frontend/dist/
        retention-days: 30
