name: Python Linting and Formatting

on:
  push:
    branches: [ main, copilot/** ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-project:
          - path: proj1/1b1_rag_dify
            python-version: '3.13'
          - path: proj2/backend
            python-version: '3.9'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-project.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-project.python-version }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      working-directory: ${{ matrix.python-project.path }}
      run: |
        uv sync --dev
    
    - name: Run Flake8
      working-directory: ${{ matrix.python-project.path }}
      run: |
        uv run flake8 .
    
    - name: Run Black --check
      working-directory: ${{ matrix.python-project.path }}
      run: |
        uv run black --check .
