name: CI & Test Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: proj2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run test
        run: bun run --filter frontend coverage

      - name: Build application
        run: bun run --filter frontend build

      - name: Test build artifacts
        run: |
          # Check that build artifacts exist
          cd frontend
          test -f dist/index.html
          test -d dist/assets

      - name: upload frontend coverage
        uses: actions/upload-artifact@v5
        with:
          name: frontend-coverage
          path: proj2/frontend/coverage/lcov.info
          retention-days: 30

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proj2/backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: |
            proj2/backend/uv.lock
            proj2/backend/pyproject.toml

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests with coverage
        run: uv run -m pytest --cov --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v5
        with:
          name: backend-coverage
          path: proj2/backend/coverage.xml
          retention-days: 30

  upload-coverage:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download frontend coverage artifact
        uses: actions/download-artifact@v6
        with:
          name: frontend-coverage

      - name: Download backend coverage artifact
        uses: actions/download-artifact@v6
        with:
          name: backend-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: frontend,backend
          name: proj2-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
